# Generated by Django 4.2.6 on 2023-11-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("audibook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatbooking",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seat_bookings",
                to="audibook.auditoriumevent",
            ),
        ),
    ]
