# Generated by Django 4.2.6 on 2023-11-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audibook", "0002_seatbooking_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatbooking",
            name="seat_column",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seatbooking",
            name="seat_row",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
